### ISSUE TITLE
Error when nothing is entered in a nullable startup option

### ISSUE THREAD

**Issue by TheBlueKingLP** [pterodactyl/panel#2433]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0-rc6
* Server's OS: `Red Hat Enterprise Linux release 8.2 (Ootpa)`
* Your Computer's OS & Browser: `Darwin hatenosaidan 19.5.0 Darwin Kernel Version 19.5.0: Tue Apr 28 22:25:09 PDT 2020; root:xnu-6153.122.1~1/RELEASE_ARM64_T8015 iPhone10,2 arm64 D21AP Darwin` with `Safari`

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: `php -v` (the php version in use).
```
PHP 7.4.9 (cli) (built: Aug  4 2020 08:28:13) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.9, Copyright (c), by Zend Technologies
```

**To Reproduce**
1. Install or create an egg with a nullable string startup option
2. Create a server with that egg
3. Go to startup tab
4. Type something in the field with a nullable string
5. Delete everything in that field after it saves
6. See error below:
![スクリーンショット 2020-09-30 19 53 55](https://user-images.githubusercontent.com/12997043/94715974-d9bc5000-0356-11eb-8059-8f2d09ced08d.png)
console: 
![スクリーンショット 2020-09-30 19 56 14](https://user-images.githubusercontent.com/12997043/94716391-7121a300-0357-11eb-8a1c-16b28b5f5373.png)
Laravel log:
```
[2020-10-01 00:56:26] production.ERROR: ErrorException: Undefined index: meta in /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/app/Exceptions/Handler.php:193
Stack trace:
#0 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/app/Exceptions/Handler.php(193): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 [internal function]: Pterodactyl\Exceptions\Handler->Pterodactyl\Exceptions\{closure}()
#2 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/vendor/laravel/framework/src/Illuminate/Support/Collection.php(638): array_map()
#3 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/app/Exceptions/Handler.php(199): Illuminate\Support\Collection->map()
#4 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(262): Pterodactyl\Exceptions\Handler->invalidJson()
#5 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(205): Illuminate\Foundation\Exceptions\Handler->convertValidationExceptionToResponse()
#6 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/app/Exceptions/Handler.php(159): Illuminate\Foundation\Exceptions\Handler->render()
#7 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(51): Pterodactyl\Exceptions\Handler->render()
#8 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Pipeline->handleException()
#9 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/app/Http/Middleware/Api/Client/Server/AuthenticateServerAccess.php(84): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#10 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Pterodactyl\Http\Middleware\Api\Client\Server\AuthenticateServerAccess->handle()
#11 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/app/Http/Middleware/Api/AuthenticateIPAccess.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#12 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Pterodactyl\Http\Middleware\Api\AuthenticateIPAccess->handle()
#13 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/app/Http/Middleware/Api/AuthenticateKey.php(82): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#14 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Pterodactyl\Http\Middleware\Api\AuthenticateKey->handle()
#15 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/app/Http/Middleware/Api/ApiSubstituteBindings.php(75): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#16 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/app/Http/Middleware/Api/Client/SubstituteClientApiBindings.php(60): Pterodactyl\Http\Middleware\Api\ApiSubstituteBindings->handle()
#17 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Pterodactyl\Http\Middleware\Api\Client\SubstituteClientApiBindings->handle()
#18 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/app/Http/Middleware/Api/IsValidJson.php(36): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#19 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Pterodactyl\Http\Middleware\Api\IsValidJson->handle()
#20 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(58): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#21 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Session\Middleware\AuthenticateSession->handle()
#22 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/app/Http/Middleware/Api/SetSessionDriver.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#23 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Pterodactyl\Http\Middleware\Api\SetSessionDriver->handle()
#24 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#25 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Routing\Middleware\ThrottleRequests->handle()
#26 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#27 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
#28 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Session\Middleware\StartSession->handle()
#29 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#30 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\Pipeline\Pipeline->then()
#31 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\Routing\Router->runRouteWithinStack()
#32 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\Routing\Router->runRoute()
#33 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\Routing\Router->dispatchToRoute()
#34 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\Routing\Router->dispatch()
#35 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#36 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#37 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle()
#38 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#39 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#40 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#41 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#42 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#43 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
#44 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#45 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#46 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#47 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
#48 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#49 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\Pipeline\Pipeline->then()
#50 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#51 /var/www/DOMAIN_REDACTED/SUBDOMAIN_REDACTED/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle()
#52 {main}  
```

**Expected behavior**
No error will pop up and field will save properly

**Comment by DaneEveritt** [comment]
Please include the actual error, not just "see error" so that we can all be on the same page as to what _you_ are seeing and expecting.

**Comment by TheBlueKingLP** [comment]
> Please include the actual error, not just "see error" so that we can all be on the same page as to what _you_ are seeing and expecting.

Updated issue with screenshots and logs

**Comment by DaneEveritt** [comment]
Oh this is already fixed on develop. 😅

**Comment by TheBlueKingLP** [comment]
Just installed the latest update(rc7) but the error now changed to `Error The value must be a string.` while the egg allows a null string (the input rule is set to `nullable|string`) to be entered to the variable.

**Comment by TheBlueKingLP** [comment]
@DaneEveritt please reopen this issue as it isn't fixed, the `nullable|string` input rule stills doesn't allow empty string to be saved
