### ISSUE TITLE
Server stuck on "Finished pulling Docker container image"

### ISSUE THREAD

**Issue by MikolajKolek** [pterodactyl/panel#3383]
**Background**:
* Panel or Wings: Wings
* Version of Panel/Wings: Latest
* Panel Logs: http://bin.ptdl.co/iskez (from what I can see only STMP errors, I didn't set up STMP so it's probably unrelated)
* Wings Logs: https://ptero.co/zukuhuyuwu
* Server's OS: Canonical-Ubuntu-20.04-aarch64-2021.05.13-0
* Your Computer's OS & Browser: Windows / Chrome
(Note: I am using an ARM server on Oracle Cloud on the new _Always Free Eligible_ Ampere shape)
(Note: I tried to get help on the Discord already but no one seems to respond)

**Describe the bug**: 
Whenever I create a new Minecraft server, it completes the install and then stops. Turning the server on again results in this getting put in the console: https://hastebin.com/qefusigaxo.md followed by a bunch of newlines that fill the entire console. On subsequent restarts, the same problem appears, but the newlines don't appear anymore. The server.jar file is never run. The issue happens with Forge, Paper and Vanilla, I haven't tried Bungee or Sponge but I assume it would be the same.

Wings `uname -a` result: `Linux pterodactyl-instance 5.4.0-1045-oracle #49-Ubuntu SMP Mon May 3 05:27:18 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux`

Wings `docker info` result: https://ptero.co/oxakiteneq.js
(Note: I turned swap on in `/etc/default/grub` but it's still showing `WARNING: No swap limit support` in `docker info`
Here's the line from the file: `GRUB_CMDLINE_LINUX_DEFAULT="quiet splash, swapaccount=1"`
I just moved on because I saw that it wasn't necessary, but I still thought it was strange and might have something to do with the issue)
Here's a screenshot of my test server's configuration: 
![image](https://user-images.githubusercontent.com/68162257/120099833-facf7d80-c13d-11eb-9021-d676c170aacf.png)

**To Reproduce**
Steps to reproduce this behaviour:
1. Set up Pterodactyl and Wings
2. Create a new Minecraft server
3. Look at the server's console

**Expected behaviour**
The server.jar file starting and the server booting up

**Comment by hwalker928** [comment]
Regarding the swap account, remove the `,` and that should fix it!

**Comment by MikolajKolek** [comment]
Sadly, that doesn't seem to fix the issue. On the topic of the actual problem, I managed to figure out that it's probably not working because I'm using the standard docker images instead of ARM docker images. I'm still unsure how I can use ARM images. I've tried changing the image to `ghcr.io/matthewpi/images:java8` but the same problems occur.

**Comment by matthewpi** [comment]
> Sadly, that doesn't seem to fix the issue. On the topic of the actual problem, I managed to figure out that it's probably not working because I'm using the standard docker images instead of ARM docker images. I'm still unsure how I can use ARM images. I've tried changing the image to `ghcr.io/matthewpi/images:java8` but the same problems occur.

My images are no longer built for arm64 as many of the base images don't support arm.

**Comment by MikolajKolek** [comment]
Because no images existed, I had to make some myself. To anyone having the same issue, here's the link: https://github.com/MikolajKolek/pterodactyl-images-arm64, they're probably not perfect but they work. This solves the problem

**Comment by yashendra2797** [comment]
I'm running into the same issue, and using both yours' and Software Noob's arm64 images for J16 don't work. Any idea why?
