### ISSUE TITLE
Schedules never end and make my server freeze every second.

### ISSUE THREAD

**Issue by Maelep** [pterodactyl/panel#3572]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

![image](https://user-images.githubusercontent.com/53207714/130595920-5445bb69-678b-4251-9f04-784c7fade99a.png)

At starts, the first message is sent then my server freeze every second and the second message is never sent.
The schedule never end (stuck in `processing`) so my server freeze indefinitely.
I have to disable the schedule to stop it.

### Expected Behavior

No lag and execute the schedule.

### Steps to Reproduce

Create a schedule similar to mine and run it.

### Panel Version

1.5.1

### Wings Version

1.4.7

### Error Logs

```bash
Wings: https://ptero.co/vuceqovixo


Panel: tail: cannot open '/var/www/pterodactyl/storage/logs/laravel-2021-08-24.log' for reading: No such file or directory
root:~# ls /var/www/pterodactyl/storage/logs/
laravel-2021-07-19.log  laravel-2021-07-20.log  laravel-2021-08-09.log
```
```

**Comment by parkervcp** [comment]
What game is this for?

**Comment by Maelep** [comment]
I'm hosting a Rust server.

**Comment by trenutoo** [comment]
Schedule being stuck should not affect the server. It being stuck processing usually indicates queue worker not working, which is fixed by restarting it and viewing its status to ensure it's running. 

I disabled the queue worker and made a schedule set to processing without any performance issues caused by it.

**Comment by Maelep** [comment]
Can you explain how to restart, view status and disable it?

**Comment by trenutoo** [comment]
`systemctl restart pteroq.service` and `systemctl status pteroq service`. It's the queue worker service that you would've created during the installation.

**Comment by Maelep** [comment]
I had a warning asking me to restart daemon. I did it then restarted `pteroq.service` and tried to launch a schedule. It looks working, I'll wait tomorrow morning for confirmation because I can't restart my server now.

**Comment by trenutoo** [comment]
@Maelep, I assume this is solved due to lack of further response?

**Comment by Maelep** [comment]
Sorry, I forgot to close the issue.
Yes, I had to restart the service and it working now.
But I still don't know why it stopped working without reason :/
I hope it will not appear again.
