### ISSUE TITLE
Incomptable basic egg do to migration.

### ISSUE THREAD

**Issue by ItJustFox** [pterodactyl/panel#3887]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Crash server when start it do to an installation unfinished / incomplete

### Expected Behavior

An normal server with a basic start.

### Steps to Reproduce

Go to 'Servers'
Click on 'Server'
Click create a gmod server
Start the Server after the install
Error will show in console.

### Panel Version

1.6.6

### Wings Version

1.5.3

### Error Logs

```bash
https://pastebin.com/f3dBG18f - Server logs with error 139
https://pastebin.com/J7qT2zuQ - Packet error " lib32gcc " that is not dowload.
```

**Comment by ItJustFox** [comment]
With your migration from debian:buster-slim to debian:bullseye-slim (That can be found [here](https://github.com/pterodactyl/yolks/blob/master/installers/debian/Dockerfile)). The eggs for Source-engine : Garry's Mod server is not able to work normally do to the fact this BASIC eggs for pterodactyl panel is made for work with debian:buster-slim and not your patch version that your currently using called debian:bullseye-slim 
And we can found that really simple with just go in the admin panel -> Nest -> Source Engine -> Garry'sMod -> Install Scrip has you can see too in the screen.
![image](https://user-images.githubusercontent.com/42358087/149656683-31294ebb-54fb-4486-b7bd-11032b3cf7b7.png)

(PS : I am totally not a developper or anything else, I am just a normal person who try to do thing and, I have been totally disappoint from seeing that in my old [ticket](https://github.com/pterodactyl/panel/issues/3885) you just closed it without saying anything or any help, so I have just search a bit.)

**Comment by Railline** [comment]
omg i have this problem but i didn't see in egg install script. i just see the repertory used (bullseye) durring the installlation of my server

**Comment by gOOvER** [comment]
Change line 7 in install Script to

`apt -y --no-install-recommends install curl lib32gcc-s1 ca-certificates`

Or remove the whole apt thing

Looks like, its fixed in repo allready

**Comment by gOOvER** [comment]
> With your migration from debian:buster-slim to debian:bullseye-slim (That can be found [here](https://github.com/pterodactyl/yolks/blob/master/installers/debian/Dockerfile?rgh-link-date=2022-01-16T10%3A43%3A05Z)). The eggs for Source-engine : Garry's Mod server is not able to work normally do to the fact this BASIC eggs for pterodactyl panel is made for work with debian:buster-slim and not your patch version that your currently using called debian:bullseye-slim And we can found that really simple with just go in the admin panel -> Nest -> Source Engine -> Garry'sMod -> Install Scrip has you can see too in the screen. ![image](https://user-images.githubusercontent.com/42358087/149656683-31294ebb-54fb-4486-b7bd-11032b3cf7b7.png)
> 
> (PS : I am totally not a developper or anything else, I am just a normal person who try to do thing and, I have been totally disappoint from seeing that in my old [ticket](https://github.com/pterodactyl/panel/issues/3885) you just closed it without saying anything or any help, so I have just search a bit.)

Ignore this. This is only a comment ;)

**Comment by ItJustFox** [comment]
> > With your migration from debian:buster-slim to debian:bullseye-slim (That can be found [here](https://github.com/pterodactyl/yolks/blob/master/installers/debian/Dockerfile?rgh-link-date=2022-01-16T10%3A43%3A05Z)). The eggs for Source-engine : Garry's Mod server is not able to work normally do to the fact this BASIC eggs for pterodactyl panel is made for work with debian:buster-slim and not your patch version that your currently using called debian:bullseye-slim And we can found that really simple with just go in the admin panel -> Nest -> Source Engine -> Garry'sMod -> Install Scrip has you can see too in the screen. ![image](https://user-images.githubusercontent.com/42358087/149656683-31294ebb-54fb-4486-b7bd-11032b3cf7b7.png)
> > (PS : I am totally not a developper or anything else, I am just a normal person who try to do thing and, I have been totally disappoint from seeing that in my old [ticket](https://github.com/pterodactyl/panel/issues/3885) you just closed it without saying anything or any help, so I have just search a bit.)
> 
> Ignore this. This is only a comment ;)

I think you didn't read all my comment to say that.

**Comment by gOOvER** [comment]
> 

No need to read all. I know this and it looks like, the whole apt install thing was removed in Repo, because all packages are installed in image

**Comment by gOOvER** [comment]
THats the new installscript. Complete install is removed. ;)

```
#!/bin/bash
# steamcmd Base Installation Script
#
# Server Files: /mnt/server

## just in case someone removed the defaults.
if [ "${STEAM_USER}" == "" ]; then
    echo -e "steam user is not set.\n"
    echo -e "Using anonymous user.\n"
    STEAM_USER=anonymous
    STEAM_PASS=""
    STEAM_AUTH=""
else
    echo -e "user set to ${STEAM_USER}"
fi

## download and install steamcmd
cd /tmp
mkdir -p /mnt/server/steamcmd
curl -sSL -o steamcmd.tar.gz https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
tar -xzvf steamcmd.tar.gz -C /mnt/server/steamcmd
mkdir -p /mnt/server/steamapps # Fix steamcmd disk write error when this folder is missing
cd /mnt/server/steamcmd

....
```

Fixed with: https://github.com/pterodactyl/panel/pull/3604

**Comment by Railline** [comment]
> THats the new installscript. Complete install is removed. ;)
> 
> ```
> #!/bin/bash
> # steamcmd Base Installation Script
> #
> # Server Files: /mnt/server
> 
> ## just in case someone removed the defaults.
> if [ "${STEAM_USER}" == "" ]; then
>     echo -e "steam user is not set.\n"
>     echo -e "Using anonymous user.\n"
>     STEAM_USER=anonymous
>     STEAM_PASS=""
>     STEAM_AUTH=""
> else
>     echo -e "user set to ${STEAM_USER}"
> fi
> 
> ## download and install steamcmd
> cd /tmp
> mkdir -p /mnt/server/steamcmd
> curl -sSL -o steamcmd.tar.gz https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
> tar -xzvf steamcmd.tar.gz -C /mnt/server/steamcmd
> mkdir -p /mnt/server/steamapps # Fix steamcmd disk write error when this folder is missing
> cd /mnt/server/steamcmd
> 
> ....
> ```
> 
> Fixed with: #3604

i have try that and the server still crash and i have this in fail state

LOAD FROM FILE FAILED resource/serverevents.res
LOAD FROM FILE FAILED resource/serverevents.res

LOAD FROM FILE FAILED resource/serverevents.re

**Comment by ItJustFox** [comment]
> Change line 7 in install Script to
> 
> `apt -y --no-install-recommends install curl lib32gcc-s1 ca-certificates`
> 
> Looks like, its fixed in repo allready


I have changed the lignes by what you say, the server is keep crashing like before, still have the same problem for me.
Still that error :
https://pastebin.com/f3dBG18f - Server logs with error 139
(Or if you dont want look. typically the same that @Railline)

**Comment by gOOvER** [comment]
> > Change line 7 in install Script to
> > `apt -y --no-install-recommends install curl lib32gcc-s1 ca-certificates`
> > Looks like, its fixed in repo allready
> 
> I have changed the lignes by what you say, the server is keep crashing like before, still have the same problem for me. Still that error : [pastebin.com/f3dBG18f](https://pastebin.com/f3dBG18f) - Server logs with error 139 (Or if you dont want look. typically the same that @Railline)

Use Discord for support.

**Comment by ItJustFox** [comment]
> > > Change line 7 in install Script to
> > > `apt -y --no-install-recommends install curl lib32gcc-s1 ca-certificates`
> > > Looks like, its fixed in repo allready
> > 
> > 
> > I have changed the lignes by what you say, the server is keep crashing like before, still have the same problem for me. Still that error : [pastebin.com/f3dBG18f](https://pastebin.com/f3dBG18f) - Server logs with error 139 (Or if you dont want look. typically the same that @Railline)
> 
> Use Discord for support.

I aleadry asked on discord without any answer. 
If I come here it's for first report a bug.

**Comment by gOOvER** [comment]
Test it some mins before. Server works without problems.

```Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
Success! App '4020' already up to date.
container@pterodactyl~ ./srcds_run -game garrysmod -console -port 27019 +ip 0.0.0.0 +host_workshop_collection +map gm_flatgrass +gamemode sandbox -strictportbind -norestart +sv_setsteamaccount +maxplayers 32 -tickrate 22 -disableluarefresh
Auto detecting CPU
Using default binary: ./srcds_linux
Couldn't load shader dll: game_shader_generic_garrysmod_srv.soConVarRef mat_dxlevel doesn't point to an existing ConVar
Game_srv.so loaded for "Garry's Mod"
Setting breakpad minidump AppID = 4000
Initializing Steam libraries for Workshop..
[S_API] SteamAPI_Init(): Loaded local 'steamclient.so' OK.
CAppInfoCacheReadFromDiskThread took 1 milliseconds to initialize
[S_API FAIL] Tried to access Steam interface SteamUser021 before SteamAPI_Init succeeded.
WS: No +host_workshop_collection or it is invalid!
Could not find steamerrorreporter binary. Any minidumps will be uploaded in-processUnknown command "cl_cmdrate"
Unknown command "cl_updaterate"
Unknown command "rate"
"host_workshop_collection" = ""
 game
Usage: sv_setsteamaccount <login_token>
Network: IP 0.0.0.0, mode MP, dedicated Yes, ports 27019 SV / 27005 CL
Error loading cfg/trusted_keys_base.txt
Error loading cfg/pure_server_minimal.txt
PREP OK
ConVarRef room_type doesn't point to an existing ConVar
Executing dedicated server config file server.cfg
Using map cycle file cfg/mapcycle.txt.
Initializing Steam libraries for secure Internet server
[S_API] SteamAPI_Init(): Loaded local 'steamclient.so' OK.
CAppInfoCacheReadFromDiskThread took 2 milliseconds to initialize
No account token specified; logging into anonymous game server account.  (Use sv_setsteamaccount to login to a persistent account.)
'banned_ip.cfg' not present; not executing.
'banned_user.cfg' not present; not executing.
Connection to Steam servers successful.
   Public IP is 5xx.xx.xx.
Assigned anonymous gameserver Steam ID [A-1:3985117189(19360)].
container@pterodactyl~ Server marked as running...
VAC secure mode is activated.
```

**Comment by gOOvER** [comment]
> > Use Discord for support.
> 
> I aleadry asked on discord without any answer. If I come here it's for first report a bug.

It is not a Bug ;)

**Comment by ItJustFox** [comment]
> > > Use Discord for support.
> > 
> > 
> > I aleadry asked on discord without any answer. If I come here it's for first report a bug.
> 
> It is not a Bug ;)

So if it's not a bug what it is ? AND why do we have that ?

**Comment by gOOvER** [comment]
> > > > Use Discord for support.
> > > 
> > > 
> > > I aleadry asked on discord without any answer. If I come here it's for first report a bug.
> > 
> > 
> > It is not a Bug ;)
> 
> So if it's not a bug what it is ? AND why do we have that ?

idk. For me the server works. mb to less diskspace. you don't post the install.log

**Comment by ItJustFox** [comment]
So there is a bug or a problem somewhere.

**Comment by gOOvER** [comment]
> So there is a bug or a problem somewhere.

yes, on your Server :)

Reinstall the server and post the install.log

**Comment by ItJustFox** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues before opening this issue.
> 
> ### Current Behavior
> Crash server when start it do to an installation unfinished / incomplete
> 
> ### Expected Behavior
> An normal server with a basic start.
> 
> ### Steps to Reproduce
> Go to 'Servers' Click on 'Server' Click create a gmod server Start the Server after the install Error will show in console.
> 
> ### Panel Version
> 1.6.6
> 
> ### Wings Version
> 1.5.3
> 
> ### Error Logs
> ```shell
> https://pastebin.com/f3dBG18f - Server logs with error 139
> https://pastebin.com/J7qT2zuQ - Packet error " lib32gcc " that is not dowload.
> ```

There is aleadry here the install logs

**Comment by gOOvER** [comment]
btw:

duplicate: https://github.com/pterodactyl/panel/issues/3885

You will not getting any other answers, when u open multiple Reports for the same error

**Comment by ItJustFox** [comment]
> btw:
> 
> duplicate: #3885
> 
> You will not getting any other answers, when u open multiple Reports for the same error

BTW : When we got CLOSED ticket for no reason without any explication or other. I need re make it with more explication.

**Comment by dapillc** [comment]
> BTW : When we got CLOSED ticket for no reason without any explication or other. I need re make it with more explication.
https://github.com/pterodactyl/panel/issues/3885#issuecomment-1013649920

**Comment by matthewpi** [comment]
> btw:
> 
> duplicate: #3885
> 
> You will not getting any other answers, when u open multiple Reports for the same error

You aren't providing anything to this conversation and aren't being helpful.  Quit acting like a moderator and giving unhelpful replies.

---

The egg you are using is out of date, there was an update on December 4th which hasn't been released yet.  Try importing https://raw.githubusercontent.com/pterodactyl/panel/develop/database/Seeders/eggs/source-engine/egg-garrys-mod.json as a new egg and creating a fresh server with it.

If that doesn't work, I'm not sure what to tell you; you are always welcome to ask for support in our [Discord](https://discord.gg/pterodactyl) where you may or may not find solutions to your problem.  If you or someone finds an issue with the egg, a PR to fix the egg is welcome and appreciated.

I highly doubt this is an issue with this software other than potentially with the egg itself.  I don't intend to spend anytime looking into this unless it is directly caused by our software, especially since other people seem to be using that egg just fine.

**Comment by parkervcp** [comment]
I installed with the current in-panel egg with no issues.
