### ISSUE TITLE
Schedule next_run does not take daylight savings time into account

### ISSUE THREAD

**Issue by m0uka** [pterodactyl/panel#4025]
### Current Behavior

Currently, due to the change to daylight savings time, every schedule that was previously executed yesterday was executed an hour later.
I am guessing it happens because next_run_at is being set when the previous schedule executes, causing the resulting date to not include DST. 

### Expected Behavior

The schedule should be executed at the same time every time.
Maybe make next_run_at use UTC, so there won't be any problems with DST (make getNextRunDate return UTC, and instead of NOW() use UTC_TIMESTAMP())?

### Steps to Reproduce

1. Create a schedule that executes every day at 12:00
2. Wait until daylight savings time starts
3. The day DST starts, the schedule will execute an hour later

### Panel Version

1.7.0

### Wings Version

1.6.1

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by parkervcp** [comment]
This should depend on your system time.

**Comment by m0uka** [comment]
The system time is correct, now the schedules are running normally, but if the previous schedule ran without DST, then the next would run +1 hour later, after that everything is normal

**Comment by DaneEveritt** [comment]
Seems more like a bug with the cron library. I don't actually have any particularly special logic that would be the culprit.

https://github.com/pterodactyl/panel/blob/14cc98f75f405fccf9353e8c989c9a33ffe9c1fd/app/Models/Schedule.php#L133-L140

**Comment by m0uka** [comment]
Apparently not a bug - https://github.com/mtdowling/cron-expression/issues/116
What about refactoring it to use UTC? I know this is a really minor issue, but it can be annoying and confusing to some people.

**Comment by DaneEveritt** [comment]
Guessing it might be a bug that was long fixed in https://github.com/dragonmantank/cron-expression which is the actual library we use, in which case it will likely end up fixed in coming weeks as we update dependencies and push out those changes.

**Comment by jchambo** [comment]
> Guessing it might be a bug that was long fixed in https://github.com/dragonmantank/cron-expression which is the actual library we use, in which case it will likely end up fixed in coming weeks as we update dependencies and push out those changes.

Was this ever looked into / resolved? I'm still seeing this myself in Schedules.

![image](https://github.com/pterodactyl/panel/assets/26009241/1b89ba6e-7d9b-415f-8e9a-eee66a07a849)

You can see these are actually offset by an hour, and have been since Daylight Savings changed on 03/12/2023.

**Comment by LevyWilson** [comment]
It's 2025. Issue is still happening.

![Image](https://github.com/user-attachments/assets/99a0857a-4813-47d4-8cd1-c50f1bbba6ea)
