### ISSUE TITLE
Docker image always shows version as canary

### ISSUE THREAD

**Issue by LinusOP** [pterodactyl/panel#4450]
### Current Behavior

When using the docker image for the panel, in the administrative overview the version always shows as canary under system information.

### Expected Behavior

It should display the current panel version, as happens in the stand alone version.

### Steps to Reproduce

Spin up a container using the docker container, go to the administrative overview (start page in the admin view)

### Panel Version

1.10.3

### Wings Version

1.7.2

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by matthewpi** [comment]
This should be fixed by both <https://github.com/pterodactyl/panel/commit/cbcf62086f0f086828bbecd0697102204a2312ff> and <https://github.com/pterodactyl/panel/commit/5331fd2cdb884428cd2625363e870ffc96016dd0>.

The first commit changes the build to take place on the `release` branch which has the proper version information, while the second ensures the build uses the code we already checked out in the workflow rather than making a clone specifically just for Docker BuildKit.

**Comment by LinusOP** [comment]
This is still occurring unfortunately, just upgraded to v1.11.0 and version is shown as "canary".
