### ISSUE TITLE
After changing my own panel template files nothing updates when going to web gui

### ISSUE THREAD

**Issue by CutieAshlynn** [pterodactyl/panel#5017]
### Current Behavior

When i go to update my custom made panel template such as the color of something or the text of something within one of the file and i save the file and go to the console for the panel and then clear all the server side cache data and configs cache data then restart the panel i dont see any change and iv already cleared my browsers cache images and cached data and nothing changed on the panel and this also is a issue when changing the backround image.

### Expected Behavior

when i go to restart the panel after saving the file it to show the new color or text i setted and the backround image.

### Steps to Reproduce

1. ftp or go to the panel file location
2. open the folders recources/scripts
3. open the css file for your panel
4. change the main color to something else in HEX color code
5. save and exit the editor
6. go to the console of the panel and clear all server side cache 
7. restart the panel
8. clear browser cache image and data
9. load up the panel and it wont load the new colors you set

Same thing for the text and backround image just make sure you select --bacground-url: url 
for the text same thing just go to a different file location that you want to edit some of the text and follow
a few of the last steps after savingthe file.

### Panel Version

1.11.5

### Wings Version

1.11.8

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by parkervcp** [comment]
I am fairly certain all the files are compiled into a compressed file and you can rebuild that with `composer install --no-dev --optimize-autoloader`

**Comment by CutieAshlynn** [comment]
Ah i see ill give it a try and let you know what happens after.
Thank you

**Comment by CutieAshlynn** [comment]
after running the command there is no change to the panel even after clear the cache data and my browsers cache data

**Comment by yesBad** [comment]
> after running the command there is no change to the panel even after clear the cache data and my browsers cache data

Which file are you modifying? You need to build the panel after modifications [like shown here](https://pterodactyl.io/community/customization/panel.html).

**Comment by CutieAshlynn** [comment]
im modifying some of the css files and a few of the files for the text and oddly when i run the command yarn build:production
it does not wanna run it throws out a error in the console.

error is got after runnning the command
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'build:production'

**Comment by CutieAshlynn** [comment]
> im modifying some of the css files and a few of the files for the text and oddly when i run the command yarn build:production it does not wanna run it throws out a error in the console.
> 
> error is got after runnning the command 00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'build:production'

this issue i fixed i did not install things correctly

**Comment by Gamer101233** [comment]
so 1 horrible issue still is active im trying to get a backround image and the main color and secondary color and tertiary color to show on the panel after updating it and building it in the css file nothing is showing on the panel even after i clear the cached data and images and the colors im using in the hex form should show on the panel and the backround image wont even load on the panel this is getting on my nerves.

im only editing the css file in the recources and scripts location and nothing i do in the and save then build the panel again works you dont see anything you edited in there am i missing something with the index and index.blade file?

pls help me on this.

**Comment by CutieAshlynn** [comment]
issue fixed fully.

**Comment by make82777** [comment]
how have you fixed it?

**Comment by yesBad** [comment]
> how have you fixed it?

https://github.com/pterodactyl/panel/issues/5017#issuecomment-1975083220
